# Read-only comparison of preserved Unity serialized blocks with the visual pass baseline.
# This reads YAML generated by Unity; it never writes scenes or prefabs.
require 'open3'
require 'json'
baseline = ARGV[0] || '6dc4906'
paths = ['Assets/_Game/Scenes/HarborPrototype.unity'] + Dir['Assets/_Game/Prefabs/*.prefab']
guids = Dir['Assets/_Game/Scripts/*.cs.meta'].map { |p| File.read(p)[/^guid: (\w+)/, 1] }
counts = Hash.new(0); changes = []; allowed_visual_changes = []
paths.each do |path|
  old, status = Open3.capture2('git', 'show', "#{baseline}:#{path}")
  raise "Baseline missing: #{path}" unless status.success?
  parse = ->(text) { text.scan(/^--- !u!(\d+) &(\d+).*?\n(.*?)(?=^--- !u!|\z)/m).to_h { |type, id, content| [id, [type.to_i, content]] } }
  before = parse.call(old); after = parse.call(File.read(path))
  before.each do |id, (type, content)|
    category = if [54, 64, 65, 135, 136, 143].include?(type)
      'physics'
    elsif type == 114 && guids.include?(content[/m_Script:.*guid: (\w+)/, 1])
      'gameplay'
    elsif type == 114 && content.include?('GlobalObjectIdHash:')
      'networkObjects'
    elsif type == 4
      'existingTransforms'
    end
    next unless category
    counts[category] += 1
    current = after[id]&.last
    if category == 'existingTransforms'
      # Child-list additions are the intended visual additions, not a geometry change.
      strip_children = ->(s) { s&.sub(/^  m_Children:.*?(?=^  m_Father:)/m, '') }
      content = strip_children.call(content); current = strip_children.call(current)
      game_object_id = content[/m_GameObject: \{fileID: (\d+)/, 1]
      if before[game_object_id]&.last&.include?('m_Name: Daylight')
        # Sun direction is intentionally part of this art task. Position/scale/parent still must match.
        strip_rotation = ->(s) { s&.gsub(/^  m_Local(?:Rotation|EulerAnglesHint):.*\n/, '') }
        allowed_visual_changes << {path: path, object: 'Daylight', property: 'rotation'} if content != current
        content = strip_rotation.call(content); current = strip_rotation.call(current)
      end
    end
    changes << { path: path, id: id, category: category } unless content == current
  end
end
puts JSON.pretty_generate({ baseline: baseline, counts: counts, allowed_visual_changes: allowed_visual_changes, preserved: changes.empty?, changes: changes })
exit(changes.empty? ? 0 : 1)
